services:
  db:
    image: docker.io/postgres:17.6
    container_name: postgres_agro
    environment:
      POSTGRES_USER: painel
      POSTGRES_PASSWORD: painel
      POSTGRES_DB: painel
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "painel" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
  app:
    build: .
    container_name: panel_app
    depends_on:
      - db
    ports:
      - "5006:5006"
    environment:
      DATABASE_URL: postgresql://painel:painel@db:5432/painel
    volumes:
      - .:/app

volumes:
  postgres_data:
